# Generated by Django 2.2.3 on 2019-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('checktime', models.DateTimeField()),
            ],
        ),
    ]
