# Generated by Django 2.2.3 on 2019-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerPrint', '0002_auto_20190727_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout1',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
