# Generated by Django 2.2.3 on 2019-07-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerPrint', '0006_auto_20190724_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FingerprintAttendence',
        ),
        migrations.AlterModelOptions(
            name='checkinout1',
            options={'managed': False},
        ),
    ]
